### ISSUE TITLE
How to change the IP address that HellRaiser binds server to?

### ISSUE THREAD

**Issue by XxLilBoPeepsxX** [m0nad/HellRaiser#70]
I'm running a headless Kali Linux cluster of Raspberry Pi's and have installed HellRaiser, the only issue is that I run everything from the command line over SSH and would like to be able to access the HellRaiser interface from the local (internal 192.168.1.xxx) IP address of my cluster, however, I am fairly unfamiliar with ruby on rails and am not quite sure how I would change the address from 127.0.0.0 to the IP address of the cluster itself. Can you help me out?

**Comment by m0nad** [comment]
I would not recommend this since HellRaiser has no authentication and the default configuration is to run in the development environment.
But if you really want to do it, I think the easiest way would be to create a nginx reverse proxy, this way you can add also basic authentication to it.
Good luck.
